### ISSUE TITLE
Error when following "Getting Started" instructions

### ISSUE THREAD

**Issue by gadfly361** [benwbooth/semitone#1]
When following the "Getting Started" instructions in the README, I get the following error after running `boot repl`.

```
gadfly ~/Desktop $ git clone https://github.com/benwbooth/semitone.git
Cloning into 'semitone'...
remote: Counting objects: 203, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 203 (delta 10), reused 0 (delta 0), pack-reused 185
Receiving objects: 100% (203/203), 81.48 KiB | 0 bytes/s, done.
Resolving deltas: 100% (80/80), done.
Checking connectivity... done.
gadfly ~/Desktop $ cd semitone/
gadfly ~/Desktop/semitone(master) $ boot repl
nREPL server started on port 52491 on host 127.0.0.1 - nrepl://127.0.0.1:52491
java.lang.ClassNotFoundException: semitone.sequencer.SemitoneSequencer, compiling:(semitone/core.clj:1:1)
    at clojure.lang.Compiler.load(Compiler.java:7239)
    at clojure.lang.RT.loadResourceScript(RT.java:371)
    at clojure.lang.RT.loadResourceScript(RT.java:362)
    at clojure.lang.RT.load(RT.java:446)
    at clojure.lang.RT.load(RT.java:412)
    at clojure.core$load$fn__5448.invoke(core.clj:5866)
    at clojure.core$load.doInvoke(core.clj:5865)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5671)
    at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
    at clojure.core$load_lib.doInvoke(core.clj:5710)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$load_libs.doInvoke(core.clj:5749)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$require.doInvoke(core.clj:5832)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at boot.repl_server$wrap_init_ns$fn__1215$fn__1217$fn__1219.invoke(repl_server.clj:28)
    at boot.repl_server$wrap_init_ns$fn__1215$fn__1217.invoke(repl_server.clj:28)
    at clojure.tools.nrepl.middleware.session$session$fn__1068.invoke(session.clj:192)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__756.invoke(middleware.clj:22)
    at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:19)
    at clojure.tools.nrepl.server$handle$fn__1137.invoke(server.clj:28)
    at clojure.core$binding_conveyor_fn$fn__4444.invoke(core.clj:1916)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: semitone.sequencer.SemitoneSequencer
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:270)
    at clojure.lang.RT.classForName(RT.java:2154)
    at clojure.lang.RT.classForNameNonLoading(RT.java:2167)
    at semitone.core$eval1247$loading__5340__auto____1248.invoke(core.clj:24)
    at semitone.core$eval1247.invoke(core.clj:24)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.eval(Compiler.java:6771)
    at clojure.lang.Compiler.load(Compiler.java:7227)
    ... 29 more
java.lang.ClassNotFoundException: semitone.sequencer.SemitoneSequencer, compiling:(semitone/core.clj:1:1)
    at clojure.lang.Compiler.load(Compiler.java:7239)
    at clojure.lang.RT.loadResourceScript(RT.java:371)
    at clojure.lang.RT.loadResourceScript(RT.java:362)
    at clojure.lang.RT.load(RT.java:446)
    at clojure.lang.RT.load(RT.java:412)
    at clojure.core$load$fn__5448.invoke(core.clj:5866)
    at clojure.core$load.doInvoke(core.clj:5865)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5671)
    at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
    at clojure.core$load_lib.doInvoke(core.clj:5710)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$load_libs.doInvoke(core.clj:5749)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$require.doInvoke(core.clj:5832)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at boot.repl_server$wrap_init_ns$fn__1215$fn__1217$fn__1219.invoke(repl_server.clj:28)
    at boot.repl_server$wrap_init_ns$fn__1215$fn__1217.invoke(repl_server.clj:28)
    at clojure.tools.nrepl.middleware.session$session$fn__1068.invoke(session.clj:192)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__756.invoke(middleware.clj:22)
    at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:19)
    at clojure.tools.nrepl.server$handle$fn__1137.invoke(server.clj:28)
    at clojure.core$binding_conveyor_fn$fn__4444.invoke(core.clj:1916)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: semitone.sequencer.SemitoneSequencer
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:270)
    at clojure.lang.RT.classForName(RT.java:2154)
    at clojure.lang.RT.classForNameNonLoading(RT.java:2167)
    at semitone.core$eval11902$loading__5340__auto____11903.invoke(core.clj:24)
    at semitone.core$eval11902.invoke(core.clj:24)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.eval(Compiler.java:6771)
    at clojure.lang.Compiler.load(Compiler.java:7227)
    ... 29 more
REPL-y 0.3.5, nREPL 0.2.8
Clojure 1.7.0
OpenJDK 64-Bit Server VM 1.7.0_65-b32
        Exit: Control+D or (exit) or (quit)
    Commands: (user/help)
        Docs: (doc function-name-here)
              (find-doc "part-of-name-here")
Find by Name: (find-name "part-of-name-here")
      Source: (source function-name-here)
     Javadoc: (javadoc java-object-or-class-here)
    Examples from clojuredocs.org: [clojuredocs or cdoc]
              (user/clojuredocs name-here)
              (user/clojuredocs "ns-here" "name-here")
user=> (play `(c d e f g a b c >))

clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: play in this context, compiling:(/tmp/boot.user6502077417334978128.clj:1:1)
             java.lang.RuntimeException: Unable to resolve symbol: play in this context
user=> 
```

**Comment by benwbooth** [comment]
Thanks for the bug report! Can you try running `boot build` before running `boot repl`? I think I forgot to put that in the build instructions. Thanks again!

**Comment by gadfly361** [comment]
Thanks for the quick feedback! After doing a `boot build` I got a new error:

```
gadfly ~/Desktop/semitone(master) $ boot build
Writing pom.xml and pom.properties...
Compiling 15 Java source files...
NOTE: /home/matthew/.boot/cache/tmp/home/matthew/Desktop/semitone/fq3/7o2s6s/semitone/sequencer/EventDispatcher.java, line -1: Some input files use unchecked or unsafe operations.
NOTE: /home/matthew/.boot/cache/tmp/home/matthew/Desktop/semitone/fq3/7o2s6s/semitone/sequencer/EventDispatcher.java, line -1: Recompile with -Xlint:unchecked for details.
Writing semitone-0.1.0.jar...
Installing semitone-0.1.0.jar...
gadfly ~/Desktop/semitone(master) $ boot repl
nREPL server started on port 41405 on host 127.0.0.1 - nrepl://127.0.0.1:41405
java.lang.ClassFormatError: Duplicate method name&signature in class file semitone/core$make_sequencer$reify__11957, compiling:(semitone/core.clj:289:28)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6730)
    at clojure.lang.Compiler.analyze(Compiler.java:6524)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
    at clojure.lang.Compiler.analyze(Compiler.java:6524)
    at clojure.lang.Compiler.analyze(Compiler.java:6485)
    at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:996)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
    at clojure.lang.Compiler.analyze(Compiler.java:6524)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
    at clojure.lang.Compiler.analyze(Compiler.java:6524)
    at clojure.lang.Compiler.analyze(Compiler.java:6485)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
    at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6179)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
    at clojure.lang.Compiler.analyze(Compiler.java:6524)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
    at clojure.lang.Compiler.analyze(Compiler.java:6524)
    at clojure.lang.Compiler.analyze(Compiler.java:6485)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
    at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6179)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
    at clojure.lang.Compiler.analyze(Compiler.java:6524)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
    at clojure.lang.Compiler.analyze(Compiler.java:6524)
    at clojure.lang.Compiler.analyze(Compiler.java:6485)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
    at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5296)
    at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3925)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721)
    at clojure.lang.Compiler.analyze(Compiler.java:6524)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
    at clojure.lang.Compiler.analyze(Compiler.java:6524)
    at clojure.lang.Compiler.access$300(Compiler.java:38)
    at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:577)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
    at clojure.lang.Compiler.analyze(Compiler.java:6524)
    at clojure.lang.Compiler.analyze(Compiler.java:6485)
    at clojure.lang.Compiler.eval(Compiler.java:6786)
    at clojure.lang.Compiler.load(Compiler.java:7227)
    at clojure.lang.RT.loadResourceScript(RT.java:371)
    at clojure.lang.RT.loadResourceScript(RT.java:362)
    at clojure.lang.RT.load(RT.java:446)
    at clojure.lang.RT.load(RT.java:412)
    at clojure.core$load$fn__5448.invoke(core.clj:5866)
    at clojure.core$load.doInvoke(core.clj:5865)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5671)
    at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
    at clojure.core$load_lib.doInvoke(core.clj:5710)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$load_libs.doInvoke(core.clj:5749)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$require.doInvoke(core.clj:5832)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at boot.repl_server$wrap_init_ns$fn__1215$fn__1217$fn__1219.invoke(repl_server.clj:28)
    at boot.repl_server$wrap_init_ns$fn__1215$fn__1217.invoke(repl_server.clj:28)
    at clojure.tools.nrepl.middleware.session$session$fn__1068.invoke(session.clj:192)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__756.invoke(middleware.clj:22)
    at clojure.tools.nrepl.middleware.load_file$wrap_load_file$fn__1124.invoke(load_file.clj:79)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__756.invoke(middleware.clj:22)
    at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:19)
    at clojure.tools.nrepl.server$handle$fn__1137.invoke(server.clj:28)
    at clojure.core$binding_conveyor_fn$fn__4444.invoke(core.clj:1916)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassFormatError: Duplicate method name&signature in class file semitone/core$make_sequencer$reify__11957
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
    at clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:46)
    at clojure.lang.Compiler$ObjExpr.getCompiledClass(Compiler.java:4833)
    at clojure.lang.Compiler$NewInstanceExpr.build(Compiler.java:7671)
    at clojure.lang.Compiler$NewInstanceExpr$ReifyParser.parse(Compiler.java:7548)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
    ... 69 more
REPL-y 0.3.5, nREPL 0.2.8
Clojure 1.7.0
OpenJDK 64-Bit Server VM 1.7.0_65-b32
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: intern in this context, compiling:(/tmp/boot.user4496451374990114754.clj:1:715)
             java.lang.RuntimeException: Unable to resolve symbol: intern in this context
#object[clojure.lang.Namespace 0x5bb97f04 "user"]
Error loading namespace; falling back to user
nil
user=> (play `(c d e f g a b c >))
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: play in this context, compiling:(/tmp/boot.user4496451374990114754.clj:1:1)
             java.lang.RuntimeException: Unable to resolve symbol: play in this context
```

**Comment by benwbooth** [comment]
I can't reproduce the error message you're getting, but I think I may have been able to fix it. Can you try doing a clean `git clone` again, and follow the build instructions again, and see if that works? Thanks!

**Comment by gadfly361** [comment]
Awesome, it works! Thanks again for helping me through this.
